// Copyright (c) 2025 YiChen. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace YcGameplayTags
{
	YICHENGAMECORE_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that game will use
	
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
	
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_ActivateSkipAvatarCheck);
	
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);
	
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	YICHENGAMECORE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);
	
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	YICHENGAMECORE_API extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	YICHENGAMECORE_API extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	YICHENGAMECORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
}


